echo -e "\n"
echo -e "The following packages extend lib32-sdl2 capabilities:"
echo -e "lib32-alsa-lib: ALSA audio driver"
echo -e "lib32-jack: JACK audio driver"
echo -e "lib32-libpulse: PulseAudio audio driver"
echo -e "lib32-pipewire: PipeWire audio driver"
echo -e " "
