#!/usr/bin/openrc-run

command=/usr/bin/gpm
command_args="
	-m ${MOUSEDEV}
	-t ${MOUSE}
	${RESPONSIVENESS:+ -r ${RESPONSIVENESS}}
	${REPEAT_TYPE:+ -R${REPEAT_TYPE}}
	${APPEND}
"

pidfile=/var/run/gpm.pid

depend() {
	need localmount
	use hotplug logger
}

start_pre() {
	if [ -z "${MOUSEDEV}" ] || [ -z "${MOUSE}" ] ; then
		eerror "You need to setup MOUSEDEV and MOUSE in /etc/conf.d/gpm first"
		return 1
	fi
}
