echo -e "\n"
echo -e "The following packages extend engrampa capabilities:"
echo -e "caja: Caja support"
echo -e "p7zip: 7Z and ARJ archive support"
echo -e "unace: ACE archive support"
echo -e "unrar: RAR archive support"
echo -e "brotli: Brotli compression support"
echo -e "rpm-tools: RPM support"
echo -e "cpio: RPM support"
echo -e " "
