echo -e "\nThe following packages extend nemo capabilities:"
echo -e "ffmpegthumbnailer: support for video thumbnails"
echo -e "catdoc: search helpers support for legacy MS Office files"
echo -e "ghostscript: search helpers support for PostScript files"
echo -e "libgsf: search helpers support for MS Office files"
echo -e "libreoffice: search helpers support for legacy MS Office powerpoint files"
echo -e "odt2txt: search helpers support for LibreOffice files"
echo -e "poppler: search helpers support for PDF"
echo -e " "
