echo -e "\n"
echo -e "The following packages extend qt6-multimedia capabilities:"
echo -e "    qt6-declarative: QML bindings"
echo -e "    gst-plugins-good: camera support, additional plugins"
echo -e "    gst-plugins-bad: camera support, additional plugins"
echo -e "    gst-plugins-ugly: additional plugins"
echo -e "    gst-libav: ffmpeg plugin"
echo -e " "
