echo -e "\n"
echo -e "================================================================================\n"
echo -e "The following packages extend grub capabilities\n"
echo -e "================================================================================\n"
echo -e "freetype: For grub-mkfont usage"
echo -e "fuse: For grub-mount usage"
echo -e "dosfstools: For grub-mkrescue FAT FS and EFI support"
echo -e "lzop: For grub-mkrescue LZO support"
echo -e "efibootmgr: For grub-install EFI support"
echo -e "libisoburn: Provides xorriso for generating grub rescue iso using grub-mkrescue"
echo -e "os-prober: To detect other OSes when generating grub.cfg in BIOS systems"
echo -e "mtools: For grub-mkrescue FAT FS support\n"
echo -e "NOTE: Run grub-mkconfig -o /boot/grub/grub.cfg to generate a configuration file."
echo -e "================================================================================\n"
