echo -e "\n"
echo -e "The following packages extend i3-wm capabilities:"
echo -e "rxvt-unicode: The terminal emulator used in the default config"
echo -e "dmenu: As menu"
echo -e "i3lock: For locking your screen"
echo -e "i3status: To display system information with a bar"
echo -e "perl-json-xs: For i3-save-tree"
echo -e "perl-anyevent-i3: For i3-save-tree"
echo -e " "
