echo -e "\n"
echo -e "The following packages extend qt5-base capabilities:"
echo -e "qt5-svg: to use SVG icon themes"
echo -e "qt5-wayland: to run Qt applications in a Wayland session"
echo -e "qt5-translations: for some native UI translations"
echo -e "postgresql-libs: PostgreSQL driver"
echo -e "mariadb-libs: MariaDB driver"
echo -e "unixodbc: ODBC driver"
echo -e "libfbclient: Firebird/iBase driver"
echo -e "freetds: MS SQL driver"
echo -e "gtk3: GTK platform plugin"
echo -e "perl: for fixqt4headers and syncqt"
echo -e " "
