echo -e " "
echo -e "The following packages extend pragha capabilities:"
echo -e "glyr: Get Artist info, Lyrics and Album arts plugin"
echo -e "grilo: DLNA Renderer plugin"
echo -e "gst-libav: Extra media codecs"
echo -e "gst-plugins-bad: Extra media codecs"
echo -e "gst-plugins-ugly: Extra media codecs"
echo -e "libcddb: Play cdrom plugin"
echo -e "libcdio-paranoia: Play cdrom plugin"
echo -e "libclastfm: Last.fm plugin"
echo -e "libkeybinder3: Global Hotkeys plugin"
echo -e "libmtp: MTP Devices plugin"
echo -e "libnotify: Notification plugin"
echo -e "libsoup: AcoustID and Get radios plugin"
echo -e " "
