echo -e "\n"
echo -e "The following packages extend openal capabilities:"
echo -e "qt5-base: alsoft-config GUI Configurator"
echo -e "fluidsynth: MIDI rendering"
echo -e "libmysofa: makemhr tool"
echo -e " "
