#!/bin/bash

# NOTE: Этот скрипт предназначен для организации очереди сборки пакетов
# WARNING: Скрипт не умеер разделять мультипакеты на категории

# Осторожнео с пакетом file
# dev-util/meson версия 0.63.3 не работает

LIST="dev-python/python-wheel
dev-python/python-build
dev-python/python-sphinx-basic-ng
dev-python/python-pygments
dev-python/python-sphinx-furo
dev-python/python-setuptools-scm
dev-python/python-jaraco.context
dev-python/python-jaraco.functools
dev-python/python-nspektr
dev-python/python-ordered-set
dev-python/python-validate-pyproject
dev-python/python-dulwich
dev-python/python-pillow
dev-python/python-virtualenv
dev-python/python-markdown-it-py
dev-python/python-zipp
dev-python/python-cachy
dev-python/python-colorama
dev-python/python-virtualenv
dev-python/python-pygments
dev-python/python-numpy
dev-python/python-keyring
dev-python/python-solidpython
dev-python/python-poetry-core
dev-python/python-poetry
dev-python/python-rich
app-crypt/p11-kit
dev-qt/qt6-webengine
app-text/asciidoc
net-libs/gupnp-igd
net-libs/libtorrent-rasterbar
gnome-base/gnome-menus(Добавить пакет)
gnome-apps/alacarte
multilib-lib32/lib32-glib2
dev-lang/zig (Требует обновить LLVM до 15й версии)
sys-fs/ncdu
media-video/obs-studio
media-libs/libquvi
kde-gear/cantor
sys-apps/file
media-libs/projectm
media-libs/libjxl
media-gfx/graphicsmagick
media-gfx/zbar
app-text/psutils
app-text/a2ps
app-text/dblatex
app-text/fbreader
app-text/openjade
app-text/texlive-bin
app-text/linuxdoc-tools
app-text/mupdf
app-text/docbook2x
app-text/pdftk
app-text/podofo
app-text/qpdf
app-text/xmldiff
app-text/xpdf
app-text/zathura
dev-java/ant
dev-java/bcprov
dev-java/eclipse-ecj
dev-java/icedtea-web
dev-java/jre-openjdk
dev-java/junit
dev-java/lucene
dev-java/rhino
dev-java/xerces
dev-cpp/clucene
dev-cpp/gtest
dev-cpp/lucene++
dev-cpp/tl-expected
dev-db/mariadb-clients
dev-db/mariadb-libs
dev-db/mongodb
dev-db/mysql
dev-db/mysql-workbench
dev-db/mytop
dev-db/postgis
dev-db/postgresql-docs
dev-db/postgresql-libs
dev-db/redis
dev-db/sqlitebrowser
net-libs/wpewebkit
net-libs/webkit2gtk
net-libs/webkit2gtk-4.1
net-libs/webkit2gtk-5.0
net-fs/samba
app-misc/beep
app-misc/far2l
gnome-libs/gcab
gnome-libs/retro-gtk
dev-libs/gobject-introspection
gnome-libs/gnome-games
app-arch/unace
app-cdr/cdemu-daemon
msgpack-c
app-editors/jedit
app-editors/neovim
app-forensics/foremost
app-i18n/poedit
app-office/abiword
app-office/gnucash
app-office/gnumeric
app-office/libreoffice
app-office/scribus
app-office/unoconv
strip-nondeterminism
media-sound/clementine
sys-power/apcupsd
xorg-apps/xorg-xdm
xorg-libs/mesa
net-voip/telepathy-salut
multilib-lib32/lib32-libx11
multilib-lib32/lib32-libxcb
app-emulation/libvirt
app-emulation/wine
dev-util/vulkan-tools
sci-libs/avogadrolibs
net-fs/cifs-utils
sys-libs/js78
games-misc/openttd
games-misc/openttd-bin
mail-mta/postfix
dev-lang/php
media-libs/opencv
www-client/firefox
www-client/seamonkey"

STARTD=`pwd`
LOGFILE=~/build.log

echo "============================= Начало сборки `date` =============================" >> $LOGFILE

for i in $LIST ; do
    cd $STARTD/$i
    if mkpkg -ba -wd ~/mkpkg/build -pod ~/mkpkg/repository -si ; then
           echo "$i ГОТОВ" >> $LOGFILE
           cd $STARTD
    else
           echo "$i НЕ СОБРАН!!!" >> $LOGFILE
           cd $STARTD
          # exit
    fi
done

echo "============================= Завершено `date` =============================" >> $LOGFILE

sudo poweroff
