#!/bin/bash

# NOTE: Этот скрипт предназначен для организации очереди сборки пакетов

# Конфликты
# python-pyproject-metadata || python-pep621
#
# python-pyxdg || python-xdg
# CudaText 1.192.0

# https://gitlab.freedesktop.org/groups/xorg/-/archived
# xorg-apps/luit
# driver/xf86-input-*: большинство драйверов больше не поддерживаются, за исключением xf86-input-libinput, xf86-input-evdev, xf86-input-keyboard, xf86-input-mouse, xf86-input-elographics, xf86-input-joystick, xf86-input-synaptics, xf86-input-vmmouse и xf86-input-void.

# php-legacy
# net-libs/grpc

# qhexedit2
# gperftools
# ocaml-compiler-libs
# gtkspell3
# ocaml-cairo
# libpst
# libytnef
# cmark
# bogofilter
# spamassassin
# amtk
# tepl
# ecl
# sbcl
# python3-dateutils
# strip-nondeterminism

# apache-orc
# google-glog
# gmock
# zeroc-ice

# libndctl
# libnvme
# sys-libs/libblockdev
# sys-fs/udisks


# mumble
# lazygit                               0.39.4-1             -> 0.40.2-1
# octave                                8.2.0-2              -> 8.3.0-2
# linux                                 6.4.10.arch1-1       -> 6.4.11.arch2-1
# linux-headers                         6.4.10.arch1-1       -> 6.4.11.arch2-1



LIST="sys-process/audit
sys-apps/highway
app-accessibility/speech-dispatcher
net-misc/modemmanager
sys-cluster/openmpi
media-video/pipewire
media-libs/webrtc-audio-processing
sys-apps/file
dev-libs/weston
app-emulation/faudio
sys-apps/less
dev-ml/fmt
x11-libs/gtk4
gnome-libs/libsecret
sys-apps/man-pages
app-text/poppler
media-libs/glu
net-libs/gnutls
media-gfx/graphicsmagick
sci-electronics/kicad
sci-electronics/kicad-library
sys-libs/libcloudproviders
dev-lang/vala
dev-libs/re2
dev-lang/luajit
dev-qt/qt5-webengine
media-libs/sdl2_mixer
sci-electronics/ngspice
sys-apps/kbd
dev-python/python-sphinx
net-libs/wvstreams
net-libs/sofia-sip
dev-libs/libmowgli
dev-libs/sqlcipher
app-text/mupdf
net-wireless/aircrack-ng
net-ftp/vsftpd
net-misc/freerdp
net-misc/remmina
www-client/links
dev-libs/thrift
net-irc/kvirc
dev-db/redis
x11-misc/x11vnc
sys-block/partimage
net-vpn/openvpn
net-mail/dovecot
net-dns/bind
dev-libs/poco
net-firewall/fwbuilder
net-misc/axel
games-misc/supertuxkart
net-ftp/gftp
app-arch/unshield
net-p2p/transmission
net-wireless/hostapd
net-libs/libircclient
net-libs/serf
net-analyzer/tcpdump
net-proxy/squid
www-client/uget
net-libs/libtorrent
net-misc/icecast
sys-libs/gwenhywfar
net-libs/imap
app-pda/libimobiledevice
app-misc/far2l
net-print/hplip
dev-libs/libxmlrpc
net-vpn/i2pd
net-ftp/proftpd
www-client/links
kde-gear/falkon
net-vpn/tor
app-admin/gkrellm
kde-frameworks/extra-cmake-modules
kde-frameworks/solid
kde-frameworks/ki18n
kde-frameworks/karchive
kde-frameworks/kdoctools
kde-frameworks/kwindowsystem
kde-frameworks/kconfig
kde-frameworks/kcoreaddons
kde-frameworks/knotifications
kde-frameworks/kauth
kde-frameworks/kcodecs
kde-frameworks/kguiaddons
kde-frameworks/kwidgetsaddons
kde-frameworks/kconfigwidgets
kde-frameworks/kitemviews
kde-frameworks/kiconthemes
kde-frameworks/kdbusaddons
kde-frameworks/kservice
kde-frameworks/kwallet
kde-frameworks/kjobwidgets
kde-frameworks/kcrash
kde-frameworks/kglobalaccel
kde-frameworks/kxmlgui
kde-frameworks/kbookmarks
kde-frameworks/kcompletion
kde-frameworks/sonnet
kde-frameworks/ktextwidgets
kde-frameworks/kded
kde-frameworks/kio
kde-frameworks/kparts
kde-frameworks/kidletime
kde-frameworks/kfilemetadata
kde-frameworks/baloo
kde-frameworks/kdesignerplugin
kde-frameworks/kunitconversion
kde-frameworks/kitemmodels
kde-frameworks/kemoticons
kde-frameworks/kdelibs4support
kde-frameworks/kpackage
kde-frameworks/kdeclarative
kde-frameworks/kcmutils
kde-frameworks/attica
kde-frameworks/syndication
kde-frameworks/knewstuff
kde-frameworks/kactivities
kde-frameworks/kwayland
kde-frameworks/kirigami2
kde-frameworks/plasma-framework
kde-frameworks/threadweaver
kde-frameworks/krunner
kde-frameworks/purpose
kde-frameworks/knotifyconfig
kde-frameworks/syntax-highlighting
kde-frameworks/ktexteditor
kde-frameworks/kdnssd
kde-frameworks/kimageformats
kde-frameworks/kplotting
kde-frameworks/networkmanager-qt
kde-frameworks/kpty
kde-frameworks/kdesu
kde-frameworks/frameworkintegration
kde-frameworks/kinit
kde-frameworks/modemmanager-qt
kde-frameworks/kpeople
kde-frameworks/kxmlrpcclient
kde-frameworks/bluez-qt
kde-frameworks/breeze-icons
kde-frameworks/oxygen-icons
kde-frameworks/kactivities-stats
kde-frameworks/prison
kde-frameworks/qqc2-desktop-style
kde-frameworks/kjs
kde-frameworks/khtml
kde-frameworks/kjsembed
kde-frameworks/kmediaplayer
kde-frameworks/kross
kde-frameworks/kholidays
kde-frameworks/kcalendarcore
kde-frameworks/kcontacts
kde-frameworks/kquickcharts
kde-frameworks/kdav
kde-frameworks/kapidox
xorg-libs/libxcb
media-sound/mac
xorg-misc/xcb-proto
xorg-base/xorg-xwayland
x11-libs/intel-media-driver
app-admin/keepassxc
sys-apps/util-linux
multilib-lib32/lib32-util-linux
xorg-libs/mesa
net-vpn/openvpn
dev-db/unixodbc
dev-lang/vala
xorg-misc/xdg-utils
sys-libs/glibc
sys-fs/lvm2
net-analyzer/net-snmp
net-misc/ntp
net-dns/openldap
media-gfx/chafa
media-libs/liblqr
media-video/ffmpeg
media-libs/libjxl
media-gfx/graphicsmagick
kde-plasma/flatpak-kcm
kde-plasma/plasma-workspace
kde-plasma/kde-cli-tools
kde-plasma/systemsettings
kde-plasma/khotkeys
kde-plasma/plasma-browser-integration
kde-plasma/powerdevil
kde-plasma/plasma-desktop
kde-plasma/plasma-sdk
media-fonts/noto-fonts
sys-apps/accountsservice
xorg-apps/xorg-xdm
dev-python/python-validate-pyproject
dev-python/python-sphinxcontrib-towncrier
dev-python/python-pip
dev-python/python-rpds-py
dev-python/python-referencing
dev-python/python-jsonschema-specifications
dev-python/python-rapidfuzz
dev-python/python-filelock
dev-python/python-regex
dev-python/python-jaraco.text
dev-python/python-jsonschema
dev-python/python-sphinx_rtd_theme
dev-python/python-uvloop
dev-python/python-anyio
dev-python/python-httpcore
dev-python/python-pylast
dev-python/python-aiohttp
dev-python/python-pytest-runner
dev-python/python-exceptiongroup
dev-python/python-webcolors
dev-python/python-genshi
dev-python/cython
dev-python/python-mpi4py
dev-python/python-breathe
dev-python/python-jaraco.classes
dev-python/python-flit-scm
dev-python/glad

dev-python/python-pyudev
dev-python/python-sphinx-furo
dev-python/python-prettytable
dev-python/python-frozenlist
dev-python/python-matplotlib
dev-python/python-inflect
dev-python/python-sphinxcontrib-towncrier
dev-python/python-utils
dev-python/python-kikit
dev-python/python-certifi
dev-python/python-hypothesis
dev-python/python-lxml
dev-python/python-css-parser
dev-python/python-distro
dev-python/python-contourpy
dev-python/python-pastel
dev-python/python-pylint
dev-python/python-uc-micro-py
dev-python/python-referencing
dev-python/python-platformdirs
dev-python/python-pyproject-metadata
dev-python/python-jsonschema-specifications
dev-python/python-markdown
dev-python/python-cachy
dev-python/python-fonttools
dev-python/python-jaraco.context
dev-python/python-rapidfuzz
dev-python/python-pyelftools
dev-python/python-solidpython
dev-python/python-editables
dev-python/python-progress
dev-python/python-wxpython
dev-python/python-pkginfo
dev-python/python-gnupg
dev-python/python-yaml
dev-python/python-sphinx-lv2-theme
dev-python/python-iniconfig
dev-python/sip
dev-python/python-mutagen
dev-python/python-cleo
dev-python/python-jaraco.functools
dev-python/python-tomlkit
dev-python/python-importlib-metadata
dev-python/python-sphinx-autodoc-typehints
dev-python/python-pam
dev-python/python-pillow
dev-python/python-rpds-py
dev-python/python-apipkg
dev-python/python-yarl
dev-python/python-termcolor
dev-python/python-docker
dev-python/python-nbxmpp
dev-python/python-tabulate
dev-python/python-nspektr
dev-python/python-click
dev-python/python-wcwidth
dev-python/python-poetry
dev-python/python-pyqt6
dev-python/python-crashtest
dev-python/python-chardet
dev-python/python-attrdict
dev-python/python-zipp
dev-python/python-pep621
dev-python/python-rapidfuzz-capi
dev-python/python-sphinxcontrib-towncrie
dev-python/python-jedi
dev-python/python-urllib3
dev-python/python-certifi
dev-python/python-fastjsonschema
dev-python/python-platformdirs
dev-python/python-zipp
dev-python/python-pillow
dev-python/python-pygment
dev-python/python-virtualenv
dev-python/python-distlib
dev-python/python-lark-parser
dev-python/python-platformdirs
dev-python/python-rapidfuzz
dev-python/python-zipp
dev-python/pypy
net-dialup/ppp
app-pda/libimobiledevice

dev-java/npm
dev-util/meson
media-libs/devil
media-libs/imlib2
media-libs/intel-media-sdk
media-libs/libjxl
media-libs/libgpod
media-libs/qtav
media-libs/projectm
media-libs/libquvi
media-libs/libtiger
media-libs/vigra
media-libs/liblqr
media-libs/ilmbase
media-libs/gnonlin
media-libs/imlib
media-libs/phonon-gstreamer
media-libs/svgalib
media-libs/chromaprint
media-libs/plib
media-libs/flickcurl
media-libs/phonon-vlc
media-libs/libofa
media-libs/giblib
media-libs/libicns
media-libs/ffmpegsource
media-libs/libv4l
media-libs/libpgf
media-libs/libmikmod
media-libs/mutagen
media-libs/quesoglc
media-libs/libiptcdata
media-libs/lcms
media-libs/stk
media-sound/gpodder
media-sound/easytag
media-sound/qjackctl
media-sound/ario
media-sound/beets
media-sound/gmpc
media-sound/kid3
media-sound/normalize
media-sound/shntool
media-sound/soundconverter
media-sound/lmms
media-sound/musique
media-sound/lash
media-sound/strawberry
media-sound/solfege
media-sound/cmus
media-sound/clementine
media-sound/foobnix
media-sound/lollypop
media-sound/pragha
media-sound/gqradio
media-sound/ardour
media-sound/audacity
media-sound/qmmp
media-video/pitivi
media-video/dvgrab
media-video/mkvtoolnix
media-video/ffmpeg2theora
media-video/dvdauthor
media-video/dirac
media-video/kino
media-video/aegisub
media-video/motion
media-video/openshot
media-video/recordmydesktop
media-video/movit
media-video/handbrake
media-video/obs-studio
multilib-lib32/lib32-curl
multilib-lib32/lib32-at-spi2-core
multilib-lib32/lib32-libcap
multilib-lib32/lib32-linux-pam
multilib-lib32/lib32-pipewire
multilib-lib32/lib32-jack
multilib-lib32/lib32-portaudio
multilib-lib32/lib32-polkit
multilib-lib32/lib32-colord
multilib-lib32/lib32-fontconfig
multilib-lib32/lib32-libxft
multilib-lib32/lib32-cairo
multilib-lib32/lib32-pango
multilib-lib32/lib32-gtk2
multilib-lib32/lib32-libdrm
multilib-lib32/lib32-libglvnd
multilib-lib32/lib32-libva
multilib-lib32/lib32-mesa
multilib-lib32/lib32-libcanberra
multilib-lib32/lib32-libepoxy
multilib-lib32/lib32-librsvg
multilib-lib32/lib32-libxkbcommon
multilib-lib32/lib32-gtk3
multilib-lib32/lib32-libpulse
multilib-lib32/lib32-fluidsynth
multilib-lib32/lib32-openal
multilib-lib32/lib32-libtheora
multilib-lib32/lib32-libvisual
multilib-lib32/lib32-gpm
multilib-lib32/lib32-aalib
multilib-lib32/lib32-imlib2
multilib-lib32/lib32-libcaca
multilib-lib32/lib32-libshout
multilib-lib32/lib32-libproxy
multilib-lib32/lib32-glib-networking
multilib-lib32/lib32-libsoup3
multilib-lib32/lib32-taglib
multilib-lib32/lib32-gstreamer
app-emulation/wine
app-emulation/wine-gecko
multilib-lib32/lib32-freetype
multilib-lib32/lib32-libwebp
multilib-lib32/lib32-libxslt
net-fs/netatalk
net-fs/davfs2
net-fs/cifs-utils
net-fs/samba
net-libs/grpc
net-libs/wpewebkit
net-libs/webkit2gtk
net-libs/webkit2gtk-4.1
net-libs/webkit2gtk-5.0
net-libs/libotr
net-libs/gupnp-igd
net-libs/gssdp
    vpnc
    stoken
    tpm2-tss
    oath-toolkit
net-vpn/openconnect
net-misc/connman
net-misc/unison
net-misc/freerdp
net-misc/bridge-utils
net-news/liferea
net-p2p/deluge
sci-libs/gdal
sci-libs/vtk
sci-libs/avogadrolibs
sci-libs/spglib
sci-libs/cln
sci-libs/netcdf
sys-apps/accountsservice
sys-apps/dbus-broker
sys-apps/flatpak
sys-apps/tcp_wrappers
sys-apps/mlocate
sys-apps/hwinfo
sys-libs/compiler-rt
sys-libs/glibc_x64x
sys-power/upower
sys-power/acpi_call
sys-process/iotop
sys-process/dcron
sys-process/latencytop
sys-process/at
www-client/seamonkey
www-client/firefox
www-client/elinks
www-client/luakit
www-client/chromium
www-client/midori
x11-libs/qscintilla
x11-libs/goffice
dev-dotnet/dotnet-sdk
dev-vcs/tortoisehg
dev-vcs/git-cola
dev-vcs/cvs
media-gfx/zbar
media-gfx/graphicsmagick
media-gfx/pinta
media-gfx/librecad
www-apache/mod_perl
www-apache/mod_wsgi
games-emulation/desmume
xorg-apps/xorg-xdm
kde-misc/calligra
kde-misc/kjots
net-voip/mumble
net-analyzer/nmap
net-analyzer/cacti
net-im/poezio
net-im/ejabberd
x11-misc/xsel
x11-misc/synergy
x11-misc/xmobar
x11-misc/wmctrl
x11-misc/xlockmore
app-editors/neovim
www-servers/nginx
sci-mathematics/maxima
mail-mta/msmtp
mail-mta/exim
sci-astronomy/stellarium
sci-astronomy/kstars
mail-client/sylpheed
mail-client/claws-mail
mail-client/mailx
sys-boot/unetbootin
sys-boot/plymouth
mail-filter/maildrop
sci-electronics/ngspice
sci-electronics/iverilog
app-antivirus/clamav
app-antivirus/clamtk
dev-scheme/slib
games-misc/widelands
xfce-extra/xfce4-artwork
xfce-extra/thunar-shares-plugin
kde-frameworks/kapidox
kde-frameworks/kapidox
kde-plasma/plasma-sdk
sys-kernel/bbswitch
sci-geosciences/qgis
sci-geosciences/liblas
dev-embedded/arduino
dev-embedded/mspdebug
dev-embedded/stm32flash
kde-gear/kitinerary
net-ftp/tftp-hpa
dev-ruby/asciidoctor
net-dialup/rp-pppoe
net-dialup/freeradius-client
dev-lua/luafilesystem
app-accessibility/flite
app-pda/usbmuxd
app-pda/libimobiledevice
dev-python/python-jaraco.classes
media-gfx/chafa
media-video/ffmpeg
dev-libs/libgudev
media-libs/liblqr
media-libs/libmfx
net-libs/libsoup
net-libs/libsoup3
media-libs/libvpx
xorg-libs/lbxinerama
dev-libs/libxslt
xorg-libs/mesa
sys-auth/polkit
app-text/poppler
app-text/qpdf
x11-misc/shared-mime-info
app-arch/snappy
sys-apps/tcp_wrappers
dev-qt/qt6-base
dev-qt/qt6-3d
dev-qt/qt6-5compat
dev-qt/qt6-charts
dev-qt/qt6-connectivity
dev-qt/qt6-datavis3d
dev-qt/qt6-declarative
dev-qt/qt6-imageformats
dev-qt/qt6-languageserver
dev-qt/qt6-lottie
dev-qt/qt6-multimedia
dev-qt/qt6-networkauth
dev-qt/qt6-positioning
dev-qt/qt6-quick3d
dev-qt/qt6-quicktimeline
dev-qt/qt6-remoteobjects
dev-qt/qt6-scxml
dev-qt/qt6-sensors
dev-qt/qt6-serialbus
dev-qt/qt6-serialport
dev-qt/qt6-shadertools
dev-qt/qt6-svg
dev-qt/qt6-tools
dev-qt/qt6-translations
dev-qt/qt6-virtualkeyboard
dev-qt/qt6-wayland
dev-qt/qt6-webchannel
dev-qt/qt6-webengine
dev-qt/qt6-websockets
dev-qt/qt6-webview
app-arch/rpm
app-arch/snappy
app-arch/mgard
app-arch/unace
app-emulation/aqemu
app-emulation/virt-manager
app-emulation/virt-viewer
app-emulation/qemu
app-emulation/virtualbox
app-emulation/winetricks
app-emulation/libvirt-glib
app-i18n/poedit
app-text/docbook-utils
app-text/poppler
app-text/qpdf
app-text/a2ps
app-text/dblatex
app-text/fbreader
app-text/libgepub
app-text/pdftk
app-text/podofo
app-text/xpdf
app-text/texlive-bin
app-text/psiconv
app-text/pandoc
app-text/mythes
app-text/asciidoc
app-office/abiword
app-office/gnucash
app-office/gnumeric
app-office/libreoffice
app-office/scribus
app-office/unoconv
app-office/homebank
dev-db/postgis
dev-db/mysql-workbench
dev-db/sqlitebrowser
dev-java/npm
dev-java/bcprov
dev-java/eclipse-ecj
dev-java/icedtea-web
dev-lang/ocaml
dev-lang/julia
dev-lang/tcc
dev-lang/mono
dev-libs/apr-util
dev-libs/js91
dev-libs/libgudev
dev-libs/libphonenumber
dev-libs/libxslt
dev-libs/nodejs-nopt
dev-libs/protobuf
dev-libs/libportal-qt5
dev-libs/tl-expected
dev-libs/cloog
dev-libs/mm
dev-libs/arrow
dev-libs/gmime
dev-libs/libx86emu
dev-libs/libdbi-drivers
dev-libs/lockdev
dev-libs/opensc
dev-libs/stfl
dev-libs/kdevelop-pg-qt
dev-libs/adios2
dev-ml/lablgtk3
dev-qt/qtcreator
dev-util/cppcheck
dev-util/pvs-studio
dev-util/how-to-use-pvs-studio-free
dev-util/apitrace
dev-util/oprofile
dev-util/gpp
dev-util/maturin
dev-python/cython
dev-python/python-certifi
dev-python/python-cleo
dev-python/python-inflect
dev-python/python-jaraco.functools
dev-python/python-jedi
dev-python/python-jsonschema
dev-python/python-platformdirs
dev-python/python-poetry
dev-python/python-rapidfuzz
dev-python/python-sphinx_rtd_theme
dev-python/python-anyio
dev-python/python-httpcore
dev-python/python-httpx
dev-python/python-jsonschema-specifications
dev-python/python-pylast
dev-python/python-referencing
dev-python/python-rpds-py
dev-python/python-trio
dev-python/python-crashtest
dev-python/python-pastel
dev-python/python-tomlkit
dev-python/python-certifi
dev-python/python-jedi
dev-python/python-urllib3
dev-python/python-jaraco.functools
dev-python/cython
dev-python/python-mutagen
gnome-apps/evolution
gnome-apps/gedit
gnome-apps/gtg
gnome-apps/lollypop
gnome-apps/gnome-power-manager
gnome-apps/gnome-mplayer
gnome-apps/gnome-terminal
gnome-base/gnome-control-center
gnome-base/gnome-session
gnome-base/gnome-shell
gnome-base/gnome-settings-daemon
gnome-base/gnome-applets
gnome-base/yelp
gnome-base/nautilus
gnome-base/gnome-panel
gnome-base/gdm
gnome-extra/yad
gnome-extra/sysprof
gnome-extra/nautilus-sendto
gnome-extra/gnome-user-share
gnome-libs/evolution-data-server
gnome-libs/gcab
gnome-libs/libgweather-4
gnome-libs/retro-gtk
gnome-libs/gnome-games
gnome-libs/gnome-online-accounts
mate-extra/atril"

STARTD=`pwd`
LOGFILE=~/Yandex.Disk

echo "============================= Начало сборки `date` =============================" >> $LOGFILE/build.log
echo "============================= Начало сборки `date` =============================" >> $LOGFILE/build_error.log

# -pod ~/Yandex.Disk/Testing_x86_64/repository/pkg

for i in $LIST ; do
    cd $STARTD/$i
#    cd "$(find $STARTD -type d -name $i | head -1)"
    if mkpkg -ba -wd ~/mkpkg/build -si -pod ~/Yandex.Disk/Testing_x86_64/repository/pkg ; then
           echo "$i" >> $LOGFILE/build.log
           cd $STARTD
    else
           echo "$i" >> $LOGFILE/build_error.log
           cd $STARTD
    fi
    sleep 1
done

echo "============================= Завершено `date` =============================" >> $LOGFILE/build.log
echo "============================= Завершено `date` =============================" >> $LOGFILE/build_error.log

mpkg-index /home/chip/Yandex.Disk/Testing_x86_64/repository/
#mpkg-update
#mpkg-upgradeall

rm -f dupes.log
rm -f index.log
rm -f package_list

sleep 240
sudo poweroff
