echo -e "\n"
echo -e "The following packages extend qmmp capabilities:"
echo -e "    mpg123: to play MP3 files"
echo -e "    flac: native FLAC support"
echo -e "    jack: JACK sound output"
echo -e "    libmpcdec: Musepack support"
echo -e "    pulseaudio: PulseAudio output"
echo -e "    pipewire: pipewire support"
echo -e "    libcdio-paranoia: Compact Disc input and control support"
echo -e "    libcddb: CDDB server support"
echo -e "    libmms: MMS stream protocol support"
echo -e "    libmodplug: MOD playing library"
echo -e "    libsndfile: sampled sound support"
echo -e "    projectm: visual efects"
echo -e "    faad2: ADTS AAC support"
echo -e "    libgme: support for chiptunes from various platforms"
echo -e "    libsidplayfp: C64 music support"
echo -e "    opusfile: Opus support"
echo -e "    wildmidi: MIDI support"
echo -e "    ffmpeg: libsamplerate wavpack"
echo -e " "
