echo -e "\n"
echo -e "The following packages extend smplayer capabilities:"
echo -e "smplayer-themes: icon themes collection"
echo -e "smplayer-skins: skin themes collection"
echo -e "smtube: browse and play youtube videos"
echo -e "youtube-dl: youtube videos and streaming"
echo -e "yt-dlp: youtube videos and streaming"
echo -e "mplayer: alternative multimedia engine"
echo -e " "
