echo -e " "
echo -e "The following packages extend gparted capabilities:"
echo -e "dosfstools: for FAT16 and FAT32 partitions"
echo -e "jfsutils: for jfs partitions"
echo -e "f2fs-tools: for Flash-Friendly File System"
echo -e "btrfs-progs: for btrfs partitions"
echo -e "exfatprogs: for exFAT partitions"
echo -e "ntfs-3g: for ntfs partitions"
echo -e "reiserfsprogs: for reiser partitions"
echo -e "udftools: for UDF file system support"
echo -e "xfsprogs: for xfs partitions"
echo -e "nilfs-utils: for nilfs2 support"
echo -e "polkit: to run gparted from application menu"
echo -e "gpart: for recovering corrupt partition tables"
echo -e "mtools: utilities to access MS-DOS disks"
echo -e "xorg-xhost: authorization from wayland"
echo -e " "
