echo -e "\n"
echo -e "The following packages extend mc capabilities:"
echo -e "aspell: spelling corrections"
echo -e "cabextract: ucab extfs"
echo -e "cdparanoia: audio extfs"
echo -e "cdrkit: iso9660 extfs"
echo -e "cvs: CVS support"
echo -e "gawk: hp48+ extfs"
echo -e "mtools: a+ extfs"
echo -e "p7zip: support for 7zip archives"
echo -e "perl: needed by several extfs scripts"
echo -e "python: to access uc1541 or s3 storage"
echo -e "python-boto: s3+ extfs"
echo -e "python-pytz: s3+ extfs"
echo -e "samba: VFS support"
echo -e "unace: uace extfs"
echo -e "unarj: uarj extfs"
echo -e "unrar: urar extfs"
echo -e "unzip: open zip archives"
echo -e "zip: uzip extfs"
echo -e " "
