echo -e "\n"
echo -e "The following packages extend vtk capabilities:"
echo -e "gnuplot: plotting tools"
echo -e "graphviz: drawing tools"
echo -e "java-runtime=11: java bindings"
echo -e "python: python bindings"
echo -e "python-mpi4py: OpenMPI python support"
echo -e "python-matplotlib: for Matplotlib rendering"
echo -e "openmpi: OpenMPI support"
echo -e "qt5-x11extras"
echo -e "tk: tcl bindings"
echo -e "adios2"
echo -e "cgns"
echo -e "ffmpeg"
echo -e "fmt"
echo -e "gdal"
echo -e "gl2ps"
echo -e "glew"
echo -e "hdf5"
echo -e "jsoncpp"
echo -e "libarchive"
echo -e "libharu"
echo -e "liblas"
echo -e "lz4"
echo -e "netcdf"
echo -e "openimagedenoise"
echo -e "openvdb"
echo -e "openvr"
echo -e "ospray"
echo -e "pdal"
echo -e "postgresql"
echo -e "proj"
echo -e "sqlite"
echo -e "unixodbc"
echo -e ""
