echo -e "\n"
echo -e "The following packages extend vlc capabilities:"
echo -e "avahi: service discovery using bonjour protocol"
echo -e "aom: AOM AV1 codec"
echo -e "gst-plugins-base-libs: for libgst plugins"
echo -e "dav1d: dav1d AV1 decoder"
echo -e "libdvdcss: decoding encrypted DVDs"
echo -e "libavc1394: devices using the 1394ta AV/C"
echo -e "libdc1394: IEEE 1394 access plugin"
echo -e "kwallet: kwallet keystore"
echo -e "libva-vdpau-driver: vdpau backend nvidia"
echo -e "libva-intel-driver: video backend intel"
echo -e "libbluray: Blu-Ray video input"
echo -e "flac: Free Lossless Audio Codec plugin"
echo -e "twolame: TwoLAME mpeg2 encoder plugin"
echo -e "libgme: Game Music Emu plugin"
echo -e "vcdimager: navigate VCD with libvcdinfo"
echo -e "libmtp: MTP devices discovery"
echo -e "systemd-libs: udev services discovery"
echo -e "smbclient: SMB access plugin"
echo -e "libcdio: audio CD playback"
echo -e "gnu-free-fonts: subtitle font "
echo -e "ttf-dejavu: subtitle font"
echo -e "libssh2: sftp access"
echo -e "libnfs: NFS access"
echo -e "mpg123: mpg123 codec"
echo -e "protobuf: chromecast streaming"
echo -e "libmicrodns: mDNS services discovery (chromecast etc)"
echo -e "lua52-socket: http interface"
echo -e "libdvdread: DVD input module"
echo -e "libdvdnav: DVD with navigation input module"
echo -e "libogg: Ogg and OggSpots codec"
echo -e "libshout: shoutcast/icecast output plugin"
echo -e "libmodplug: MOD output plugin"
echo -e "libvpx: VP8 and VP9 codec"
echo -e "libvorbis: Vorbis decoder/encoder"
echo -e "speex: Speex codec"
echo -e "opus: opus codec"
echo -e "libtheora: theora codec"
echo -e "libpng: PNG support"
echo -e "libjpeg-turbo: JPEG support"
echo -e "librsvg: SVG plugin"
echo -e "x264: H264 encoding"
echo -e "x265: HEVC/H.265 encoder"
echo -e "zvbi: VBI/Teletext/webcam/v4l2 capture/decoding"
echo -e "libass: Subtitle support"
echo -e "libkate: Kate codec"
echo -e "libtiger: Tiger rendering for Kate streams"
echo -e "sdl_image: SDL image support"
echo -e "srt: SRT input/output plugin"
echo -e "aalib: ASCII art video output"
echo -e "libcaca: colored ASCII art video output"
echo -e "libpulse: PulseAudio audio output"
echo -e "alsa-lib: ALSA audio output"
echo -e "jack: jack audio server"
echo -e "libsamplerate: audio Resampler"
echo -e "libsoxr: SoX audio Resampler"
echo -e "lirc: lirc control"
echo -e "libgoom2: Goom visualization"
echo -e "projectm: ProjectM visualisation"
echo -e "ncurses: ncurses interface"
echo -e "libnotify: notification plugin"
echo -e "gtk3: notification plugin"
echo -e "aribb24: aribsub support"
echo -e "aribb25: aribcam support"
echo -e "pcsclite: aribcam support"
echo -e " "
