echo -e "\n"
echo -e "The following packages extend subversion capabilities:"
echo -e "libgnome-keyring: for GNOME Keyring for auth credentials"
echo -e "kwallet: for KWallet for auth credentials"
echo -e "bash-completion: for svn bash completion"
echo -e "python: for some hook scripts"
echo -e "ruby: for some hook scripts"
echo -e " "
