echo -e "\n"
echo -e "The following packages extend lv2 capabilities:"
echo -e "sord: for lv2_validate"
echo -e "libsndfile: for eg-sampler.lv2"
echo -e "cairo: for eg-sampler.lv2 and eg-scope.lv2"
echo -e "fontconfig: for eg-sampler.lv2 and eg-scope.lv2"
echo -e "freetype: for eg-sampler.lv2 and eg-scope.lv2"
echo -e "glib2: for eg-sampler.lv2 and eg-scope.lv2"
echo -e "gtk2: for eg-sampler.lv2 and eg-scope.lv2"
echo -e "harfbuzz: for eg-sampler.lv2 and eg-scope.lv2"
echo -e "pango: for eg-sampler.lv2 and eg-scope.lv2"
echo -e "python-pygments: for lv2specgen.py"
echo -e "python-rdflib: for lv2specgen.py"
echo -e " "
