#!/bin/sh
MODULES="mpkgsupport nwidgets mpkg-core mpkg-console mpkg-i18n mpkg-parted mklivecd libagiliasetup agilia-text-installer agilia-gui-installer"

BUILD=${BUILD:-1}

set -e
for i in $MODULES ; do
	( cd $i && mkpkg -si -bb ${BUILD} )
done
set +e

