echo -e " "
echo -e "The following packages extend python-httpx capabilities:"
echo -e "python-brotli: for brotli response decompression"
echo -e "python-brotlicffi: for brotli response decompression"
echo -e "python-h2: HTTP/2 support"
echo -e "python-socksio: SOCKS proxy support"
echo -e "python-click: command line client support"
echo -e "python-rich: command line client support"
echo -e "python-pygments: command line client support"
echo -e "python-trio: alternative async library"
echo -e " "
