echo -e "\n"
echo -e "The following packages extend gnome-control-center capabilities:"
echo -e "    fwupd: device security panel"
echo -e "    gnome-remote-desktop: screen sharing"
echo -e "    gnome-shell: multitasking panel"
echo -e "    gnome-user-share: WebDAV file sharing"
echo -e "    malcontent: application permission control"
echo -e "    networkmanager: network settings"
echo -e "    openssh: remote login"
echo -e "    power-profiles-daemon: power profiles"
echo -e "    rygel: media sharing"
echo -e "    system-config-printer: printer settings"
echo -e " "
