echo -e "\n"
echo -e "The following packages extend rhythmbox capabilities:"
echo -e "gst-plugins-ugly: Extra media codecs"
echo -e "gst-plugins-bad: Extra media codecs"
echo -e "gst-libav: Extra media codecs"
echo -e "brasero: Audio CD Recorder plugin"
echo -e "libdmapsharing: DAAP Music Sharing plugin"
echo -e "grilo-plugins: Grilo media browser plugin"
echo -e "lirc: LIRC plugin"
echo -e "libgpod: Portable Players - iPod plugin"
echo -e "libmtp: Portable Players - MTP plugin"
echo -e "gvfs-mtp: Portable Players - Android plugin"
echo -e "zeitgeist: Zeitgeist logging plugin"
echo -e " "
