echo -e "\n"
echo -e "The following packages extend opam capabilities:"
echo -e "darcs: For downloading packages with darcs"
echo -e "git: For downloading packages with git"
echo -e "mercurial: For downloading packages with mercurial"
echo -e "rsync: For downloading packages with rsync"
