echo -e "\n"
echo -e "The following packages extend qt6-base capabilities:"
echo -e "    qt6-wayland: to run Qt6 applications in a Wayland session"
echo -e "    postgresql-libs: PostgreSQL driver"
echo -e "    mariadb-libs: MariaDB driver"
echo -e "    unixodbc: ODBC driver"
echo -e "    libfbclient: Firebird/iBase driver"
echo -e "    freetds: MS SQL driver"
echo -e "    gtk3: GTK platform plugin"
echo -e "    perl: for syncqt"
echo -e " "
