echo -e " "
echo -e "The following packages extend webkitgtk-6.0 capabilities:"
echo -e "geoclue: Geolocation support"
echo -e "gst-plugins-good: media decoding"
echo -e "gst-plugins-bad: media decoding"
echo -e "gst-libav: nonfree media decoding"
echo -e " "
