echo -e "\n"
echo -e "The following packages extend pcmanfm-qt capabilities:"
echo -e "gvfs: for various features like mounting without root, remote filesystems, encrypted filesystems and many others mentioned on https://github.com/lxqt/pcmanfm-qt/wiki"
echo -e "gvfs-mtp: MTP support (Media Transfer Protocol)"
echo -e "lxqt-archiver: archive management"
echo -e " "
