echo -e "\n"
echo -e "The following packages extend okular capabilities:"
echo -e "    ebook-tools: mobi and epub support"
echo -e "    kdegraphics-mobipocket: mobi support"
echo -e "    libzip: CHM support"
echo -e "    khtml: CHM support"
echo -e "    chmlib: CHM support"
echo -e "    calligra: ODT and ODP support"
echo -e "    unrar: Comic Book Archive support"
echo -e "    unarchiver: Comic Book Archive support (alternative)"
echo -e "    kde-cli-tools: to configure web shortcuts"
echo -e "    plasma-workspace: to configure web shortcuts"
echo -e " "

