echo -e "\n"
echo -e "The following packages extend xfce4-session capabilities:"
echo -e "gnome-keyring: for keyring support when GNOME compatibility is enabled"
echo -e "xfce4-screensaver: for locking screen with xflock4"
echo -e "xscreensaver: for locking screen with xflock4"
echo -e "gnome-screensaver: for locking screen with xflock4"
echo -e "xlockmore: for locking screen with xflock4"
echo -e "slock: for locking screen with xflock4"
echo -e " "
