echo -e " "
echo -e "The following packages extend libblockdev capabilities:"
echo -e "btrfs-progs: BTRFS plugin"
echo -e "dosfstools: VFAT filesystem support"
echo -e "lvm2: LVM plugin"
echo -e "ndctl: NVDIMM plugin"
echo -e "ntfs-3g: NTFS filesystem support"
echo -e "xfsprogs: XFS filesystem support"
echo -e " "
