echo -e "\n"
echo -e "The following packages extend plasma-desktop capabilities:"
echo -e "    plasma-nm: Network manager applet"
echo -e "    powerdevil: power management, suspend and hibernate support"
echo -e "    kscreen: screen management"
echo -e "    ibus: kimpanel IBUS support"
echo -e "    scim: kimpanel SCIM support"
echo -e "    kaccounts-integration: OpenDesktop integration plugin"
echo -e "    packagekit-qt5: to install new krunner plugins"
echo -e " "

