echo -e "\n"
echo -e "The following packages extend kontact capabilities:"
echo -e "    akregator"
echo -e "    kaddressbook"
echo -e "    kjots"
echo -e "    kmail"
echo -e "    knotes"
echo -e "    korganizer"
echo -e "    zanshin"
echo -e " "
