echo -e "\n"
echo -e "The following packages extend obs-studio capabilities:"
echo -e "    libfdk-aac: FDK AAC codec support"
echo -e "    libva-intel-driver: hardware encoding"
echo -e "    libva-mesa-driver: hardware encoding"
echo -e "    luajit: scripting support"
echo -e "    python: scripting support"
echo -e "    sndio: Sndio input client"
echo -e "    v4l2loopback-dkms: virtual camera support"
echo -e " "
