echo -e "\n"
echo -e "The following packages extend ffmpeg capabilities:"
echo -e "	avisynthplus: AviSynthPlus support"
echo -e "	intel-media-sdk: Intel QuickSync support (legacy)"
echo -e "	onevpl-intel-gpu: Intel QuickSync support"
echo -e "	ladspa: LADSPA filters"
echo -e "	nvidia-utils: Nvidia NVDEC/NVENC support\n"
