echo -e "\n"
echo -e "The following packages extend alsa-plugins capabilities:"
echo -e "dbus: for maemo plugin"
echo -e "ffmpeg: for pcm_a52 plugin"
echo -e "jack: for pcm_jack plugin"
echo -e "libavtp: for pcm_aaf plugin"
echo -e "libsamplerate: for rate_samplerate plugin"
echo -e "libpulse: for conf_pulse, ctl_pulse and pcm_pulse plugins"
echo -e "speexdsp: for pcm_speex and rate_speexrate plugins"
echo -e " "
