echo -e "\n"
echo -e "The following packages extend zbar capabilities:"
echo -e "    gtk3: for zbar-gtk"
echo -e "    qt5-x11extras: for zbar-qt"
echo -e "    python: for zbar python bindings"
echo -e " "
