echo -e "\n"
echo -e "The following packages extend gwenview capabilities:"
echo -e "    qt5-imageformats: support for tiff, webp, and more image formats"
echo -e "    kimageformats: support for dds, xcf, exr, psd, and more image formats"
echo -e "    kamera: import pictures from gphoto2 cameras"
echo -e " "
