echo -e "\n"
echo -e "The following packages extend frameworkintegration capabilities:"
echo -e "appstream-qt: dependency resolving via AppStream"
echo -e "packagekit-qt5: dependency resolving via AppStream"
echo -e " "
