echo -e "\nThe following packages extend git capabilities:"
echo -e "tk: gitk and git gui"
echo -e "perl-libwww: git svn"
echo -e "perl-term-readkey: git svn and interactive.singlekey setting"
echo -e "perl-io-socket-ssl: git send-email TLS support"
echo -e "perl-authen-sasl: git send-email TLS support"
echo -e "perl-mediawiki-api: git mediawiki support"
echo -e "perl-datetime-format-iso8601: git mediawiki support"
echo -e "perl-lwp-protocol-https: git mediawiki https support"
echo -e "perl-cgi: gitweb (web interface) support"
echo -e "python: git svn & git p4"
echo -e "subversion: git svn"
echo -e "libsecret: libsecret credential helper"
echo -e " "
