echo -e "\n"
echo -e "bzr: Version Control plugin"
echo -e "git: Version Control plugin"
echo -e "mercurial: Version Control plugin"
echo -e "gnuplot: Insert Gnuplot plugin"
echo -e "ditaa: Insert Ditaa plugin"
echo -e "graphviz: Insert Diagram plugin"
echo -e "xdot: Link Map plugin"
echo -e "gtkspell3: Spell Checker plugin"
echo -e "r: Insert GNU R Plot plugin"
echo -e "scrot: Insert Screenshot plugin"
echo -e "lilypond: Insert Score plugin"
echo -e "gtksourceview3: Source View plugin"
echo -e "texlive-bin: Insert Equation plugin"
echo -e " "
