echo -e "\n"
echo -e "alsa-lib: for ALSA output plugin support"
echo -e "libao: for AO output plugin support"
echo -e "libpulse: for PulseAudio output plugin support"
echo -e "faad2: for AAC input plugin support"
echo -e "ffmpeg: for ffmpeg input plugin support"
echo -e "flac: for flac input plugin support"
echo -e "jack: for jack plugin support"
echo -e "libmad: for mp3 input plugin support"
echo -e "libmodplug: for modplug input plugin support"
echo -e "libmp4v2: for mp4 input plugin support"
echo -e "libmpcdec: for musepack input plugin support"
echo -e "libsamplerate: for sampe rate converter support"
echo -e "libvorbis: for vorbis input plugin support"
echo -e "libcdio-paranoia: for cdio support"
echo -e "opusfile: for opus input plugin support"
echo -e "wavpack: for wavpack input plugin support"
echo -e " "
