echo -e "\n"
echo -e "The following packages extend soundkonverter capabilities:"
echo -e "faac: faac backend"
echo -e "faad2: faad backend"
echo -e "ffmpeg: ffmpeg backend"
echo -e "flac: flac backend"
echo -e "fluidsynth: flouidsynth backend"
echo -e "lame: lame backend"
echo -e "mac: mac backend"
echo -e "mplayer: mplayer backend"
echo -e "opus-tools: opus backend"
echo -e "speex: speexenc, speexdec backends"
echo -e "timidity++: midi backend"
echo -e "twolame: twolame backend"
echo -e "vorbisgain: vorbisgain backend"
echo -e "vorbis-tools: vorbis tools backend"
echo -e "wavpack: wavpack backend"
echo -e "sox: sox plugin (change sample rate, various effects)"
echo -e " "
