echo -e "\n"
echo -e "The following packages extend lollypop capabilities:"
echo -e "easytag: Modify tags"
echo -e "gst-libav: FFmpeg plugin for GStreamer"
echo -e "gst-plugins-bad: "Bad" plugin libraries"
echo -e "gst-plugins-base: "Base" plugin libraries"
echo -e "gst-plugins-good: "Good" plugin libraries"
echo -e "gst-plugins-ugly: "Ugly" plugin libraries"
echo -e "kid3-qt: Store covers in tags"
echo -e "libsecret: Last.FM support"
echo -e "youtube-dl: Youtube support"
echo -e " "
