#!/bin/bash

KF5_VERSION=5.109.0
BUILD_VERSION=1

LIST="extra-cmake-modules
solid
ki18n
karchive
kdoctools
kwindowsystem
kconfig
kcoreaddons
knotifications
kauth
kcodecs
kguiaddons
kwidgetsaddons
kconfigwidgets
kitemviews
kiconthemes
kdbusaddons
kservice
kwallet
kjobwidgets
kcrash
kglobalaccel
kxmlgui
kbookmarks
kcompletion
sonnet
ktextwidgets
kded
kio
kparts
kidletime
kfilemetadata
baloo
kdesignerplugin
kunitconversion
kitemmodels
kemoticons
kdelibs4support
kpackage
kdeclarative
kcmutils
attica
syndication
knewstuff
kactivities
kwayland
kirigami2
plasma-framework
threadweaver
krunner
purpose
knotifyconfig
syntax-highlighting
ktexteditor
kdnssd
kimageformats
kplotting
networkmanager-qt
kpty
kdesu
frameworkintegration
kinit
modemmanager-qt
kpeople
kxmlrpcclient
bluez-qt
breeze-icons
oxygen-icons
kactivities-stats
prison
qqc2-desktop-style
kjs
khtml
kjsembed
kmediaplayer
kross
kholidays
kcalendarcore
kcontacts
kquickcharts
kdav
kapidox"

CWD=~
STARTD=`pwd`

LOGFILE=~/build.log

echo "============================= Начало сборки `date` =============================" >> $LOGFILE

for i in $LIST ; do
    cd $STARTD/$i
    if mkpkg -ba -wd ~/mkpkg/build -si -bv $KF5_VERSION -bb $BUILD_VERSION ; then
           echo "$i" >> $LOGFILE/build.log
           cd $STARTD
    else
           echo "$i" >> $LOGFILE/build_error.log
           cd $STARTD
    fi
done

echo "============================= Завершено `date` =============================" >> $LOGFILE
