echo -e "\nThe following packages extend speech-dispatcher capabilities:"
echo -e "festival: Speech output using Festival"
echo -e "espeak-ng: Speech output using ESpeak-ng"
echo -e "pulseaudio: PulseAudio support"
echo -e " "
