echo -e " "
echo -e "The following packages extend mariadb capabilities:"
echo -e "cracklib: for cracklib plugin"
echo -e "curl: for ha_s3 plugin"
echo -e "galera: for MariaDB cluster with Galera WSREP"
echo -e "judy: for Open Query GRAPH (OQGraph) computation engine"
echo -e "perl-dbd-mariadb: for mariadb-hotcopy, mariadb-convert-table-format and mariadb-setpermission"
echo -e "python-mysqlclient: for myrocks_hotbackup"
echo -e "xz: lzma provider"
echo -e " "
