echo -e "\n"
echo -e "The following packages extend pipewire capabilities:"
echo -e "    gst-plugin-pipewire: GStreamer plugin"
echo -e "    pipewire-alsa: ALSA configuration"
echo -e "    pipewire-audio: Audio support"
echo -e "    pipewire-docs: Documentation"
echo -e "    pipewire-ffado: FireWire support"
echo -e "    pipewire-jack-client: PipeWire as JACK client"
echo -e "    pipewire-jack: JACK replacement"
echo -e "    pipewire-pulse: PulseAudio replacement"
echo -e "    pipewire-roc: ROC streaming"
echo -e "    pipewire-session-manager: Session manager"
echo -e "    pipewire-v4l2: V4L2 interceptor"
echo -e "    pipewire-x11-bell: X11 bell"
echo -e "    pipewire-zeroconf: Zeroconf support"
echo -e "    realtime-privileges: realtime privileges with rt module"
echo -e "    rtkit: realtime privileges with rtkit module"
echo -e " "
