echo -e "\n"
echo -e "The following packages extend gnome-software capabilities:"
echo -e "    flatpak: Flatpak support plugin"
echo -e "    fwupd: fwupd support plugin"
echo -e "    malcontent: Parental control plugin"
echo -e " "
