echo -e "\n"
echo -e "The following packages extend xarchiver capabilities:"
echo -e "arj: ARJ support"
echo -e "binutils: deb support"
echo -e "bzip2: bzip2 support"
echo -e "cpio: RPM support"
echo -e "gzip: gzip support"
echo -e "lha: LHA support"
echo -e "lrzip: lrzip support"
echo -e "lz4: LZ4 support"
echo -e "lzip: lzip support"
echo -e "lzop: LZOP support"
echo -e "p7zip: 7z support"
echo -e "tar: tar support"
echo -e "unarj: ARJ support"
echo -e "unrar: RAR support"
echo -e "unzip: ZIP support"
echo -e "xdg-utils: recognize more file types to open"
echo -e "xz: xz support"
echo -e "zip: ZIP support"
echo -e "zstd: zstd support"
echo -e " "
