#!/usr/bin/openrc-run

depend() {
	need net
	use logger
}

start() {
	if [ -z "${DHCRELAY_SERVERS}" ]; then
		eerror "No DHCRELAY_SERVERS specified in /etc/conf.d/dhcrelay"
		return 1
	fi

	checkpath -d /var/run/dhcp

	ebegin "Starting dhcrelay"
	start-stop-daemon --start --exec /usr/bin/dhcrelay \
		-- -q $(printf -- '-i %s ' ${IFACE}) ${DHCRELAY_OPTS} ${DHCRELAY_SERVERS}
	eend $?
}

stop() {
	ebegin "Stopping dhcrelay"
	start-stop-daemon --stop --pidfile /var/run/dhcp/dhcrelay.pid
	eend $?
}
