echo -e "\n"
echo -e "The following packages extend kde-gtk-config capabilities:"
echo -e "    gtk3: GTK3 apps support"
echo -e "    xsettingsd: apply settings to GTK applications on the fly"
echo -e " "
