echo -e "\n"
echo -e "The following packages extend apache capabilities:"
echo -e "lua: for mod_lua module"
echo -e "libxml2: for mod_proxy_html, mod_xml2enc modules"
echo -e "curl: for mod_md module"
echo -e "jansson: for mod_md module"
echo -e "brotli: for mod_brotli module"
echo -e "uwsgi: for mod_proxy_uwsgi module"
echo -e "lynx: apachectl status"
echo -e "perl: for apxs and dbmmanage"
echo -e " "
