echo -e "\n"
echo -e "The following packages extend python-pyqt5 capabilities:"
echo -e "python-opengl: enable OpenGL 3D graphics in PyQt applications"
echo -e "python-dbus: for python-dbus mainloop support"
echo -e "qt5-multimedia: QtMultimedia, QtMultimediaWidgets"
echo -e "qt5-tools: QtHelp, QtDesigner"
echo -e "qt5-svg: QtSvg"
echo -e "qt5-xmlpatterns: QtXmlPatterns"
echo -e "qt5-declarative: QtQml, qmlplugin"
echo -e "qt5-serialport: QtSerialPort"
echo -e "qt5-websockets: QtWebSockets"
echo -e "qt5-connectivity: QtNfc, QtBluetooth"
echo -e "qt5-x11extras: QtX11Extras"
echo -e "qt5-remoteobjects: QtRemoteObjects"
echo -e "qt5-speech: QtTextToSpeech"
echo -e "qt5-quick3d: QtQuick3D"
echo -e " "
