echo -e "\n"
echo -e "The following packages extend qt6-3d capabilities:"
echo -e "    qt6-shadertools: RHI renderer"
echo -e "    qt6-declarative: QML bindings"
echo -e "    assimp: assimp importer plugin"
echo -e " "
