echo -e "\n"
echo -e "The following packages extend calligra capabilities:"
echo -e "libwpg: Corel WordPerfect Graphics image importer"
echo -e "libwps: Microsoft Works file word processor format import"
echo -e "libvisio: Microsoft Visio import filter"
echo -e "libetonyek: Apple Keynote import filter"
echo -e "pstoedit: EPS to SVG filter"
echo -e "poppler: PDF to SVG filter"
echo -e "libgit2: Calligra Gemini git plugin"
echo -e "kirigami2: for Calligra Gemini"
echo -e "qt5-quickcontrols: for Calligra Gemini"
echo -e "qt5-webengine: for Calligra Gemini"
echo -e " "
