echo -e "\nThe following packages extend kimageformats capabilities:"
echo -e "libavif: AVIF format support"
echo -e "openexr: EXR format support"
echo -e "libheif: HEIF format support"
echo -e "libjxl: JPEG-XL format support"
echo -e " "
