echo -e "\n"
echo -e "The following packages extend  capabilities:"
echo -e "    qt5-imageformats: thumbnails for additional image formats"
echo -e "    perl: info kioslave"
echo -e "    kimageformats: thumbnails for additional image formats"
echo -e "    taglib: audio file thumbnails"
echo -e "    libappimage: AppImage thumbnails"
echo -e "    icoutils: Windows executable thumbnails"
echo -e "    openexr: EXR format thumbnails"
echo -e "    kactivities-stats: recently used kioslave"
echo -e " "
