echo -e "\n"
echo -e "The following packages extend inkscape capabilities:"
echo -e "fig2dev: xfig input"
echo -e "gvfs: import clip art"
echo -e "pstoedit: latex formulas"
echo -e "texlive-pstricks: latex formulas"
echo -e " "
