echo -e "\n"
echo -e "The following packages extend moc capabilities:"
echo -e "speex: for using the speex plugin"
echo -e "ffmpeg: for using the ffmpeg plugin"
echo -e "taglib: for using the musepack plugin"
echo -e "libmpcdec: for using the musepack plugin"
echo -e "wavpack: for using the wavpack plugin"
echo -e "faad2: for using the aac plugin"
echo -e "libmodplug: for using the modplug plugin"
echo -e " "
