echo -e "\n"
echo -e "The following packages extend gnome-games capabilities:"
echo -e "libretro-beetle-pce-fast: Support for TurboGrafx-16 and TurboGrafx-CD games"
echo -e "libretro-beetle-psx: Support for PlayStation games"
echo -e "libretro-blastem: Support for Sega Genesis games"
echo -e "libretro-citra: Support for Nintendo 3DS games"
echo -e "libretro-flycast: Support for Dreamcast games"
echo -e "libretro-gambatte: Support for Game Boy and Game Boy Color games"
echo -e "libretro-mgba: Support for Game Boy Advance games"
echo -e "libretro-nestopia: Support for Nintendo Entertainment System and Famicom Disk System games"
echo -e "libretro-parallel-n64: Support for Nintendo 64 games"
echo -e "libretro-picodrive: Support for Master System, Genesis 32X, Sega CD, Sega CD 32X, Sega Genesis and Sega Pico games"
echo -e " "
