echo -e "\n"
echo -e "The following packages extend tumbler capabilities:"
echo -e "ffmpegthumbnailer: video thumbnails"
echo -e "poppler-glib: PDF thumbnails"
echo -e "libgsf: ODF thumbnails"
echo -e "libgepub: EPUB thumbnails"
echo -e "libopenraw: RAW thumbnails"
echo -e "freetype: font thumbnails"
echo -e " "
