echo -e "\n"
echo -e "The following packages extend kdenlive capabilities:"
echo -e "    ffmpeg: for FFmpeg plugin"
echo -e "    dvgrab: for firewire capture"
echo -e "    recordmydesktop: for screen capture"
echo -e "    opencv: for motion tracking"
echo -e "    plasma-desktop: theme configuration"
echo -e "    opentimelineio: timeline export/import"
echo -e "    bigsh0t: VR360 effects"
echo -e "    mediainfo: for technical clip information"
echo -e "    noise-suppression-for-voice: noise suppression effect"
echo -e " "

