echo -e "\n"
echo -e "The following packages extend  capabilities:"
echo -e "gtk3: GUI frontends"
echo -e "php: generate a PHP status page for your GPS"
echo -e "php-gd: image support for the PHP status page"
echo -e "python-cairo: GUI frontends"
echo -e "python-gobject: GUI frontends"
echo -e "python-pyserial: GUI frontends"
echo -e "qt5-base: for Qgpsmm"
echo -e " "
