echo -e " "
echo -e "The following packages extend connman capabilities:"
echo -e "bluez: Support for Bluetooth devices"
echo -e "wpa_supplicant: for WiFi devices"
echo -e "pptpclient: for ppp support"
echo -e "openvpn: for VPN Support"
echo -e "iwd: for WiFi devices"
echo -e " "
