echo -e "\n"
echo -e "The following packages extend python-pyqt6 capabilities:"
echo -e "qt6-tools: QtHelp, QtDesigner bindings"
echo -e "qt6-svg: QtSvg bindings"
echo -e "qt6-declarative: QtQml bindings, qmlplugin"
echo -e "qt6-quick3d: QtQuick3D bindings"
echo -e "qt6-connectivity: QtBluetooth, QtNfc bindings"
echo -e "qt6-multimedia: QtMultimedia bindings"
echo -e "qt6-positioning: QtPositioning bindings"
echo -e "qt6-remoteobjects: QtRemoteObjects bindings"
echo -e "qt6-sensors: QtSensors bindings"
echo -e "qt6-serialport: QtSerialPort bindings"
echo -e "qt6-webchannel: QtWebChannel bindings"
echo -e "dbus-python: for python-dbus mainloop support"
echo -e " "
