echo -e "\n"
echo -e "The following packages extend inkscape capabilities:"
echo -e "fig2dev: xfig input"
echo -e "gvfs: import clip art"
echo -e "pstoedit: latex formulas"
echo -e "scour: optimized SVG output, some extensions"
echo -e "texlive-core: latex formulas"
echo -e " "
