echo -e "\n"
echo -e "The following packages extend efl capabilities:"
echo -e "gst-plugins-base: Video and thumbnail codecs"
echo -e "gst-plugins-good: Video and thumbnail codecs"
echo -e "gst-plugins-bad: Video and thumbnail codecs"
echo -e "gst-plugins-ugly: Video and thumbnail codecs"
echo -e "gst-libav: Video and thumbnails with ffmpeg/libav"
echo -e "libraw: RAW image loader"
echo -e "libreoffice: Office document loader"
echo -e "librsvg: SVG loader"
echo -e "libspectre: PostScript loader"
echo -e "poppler: PDF loader"
echo -e "scim: IM module for SCIM"
echo -e " "
