echo -e "\n"
echo -e "The following packages extend pinentry capabilities:"
echo -e "	gtk2: gtk2 backend"
echo -e "	qt5-base: qt backend"
echo -e "       kwayland: qt backend"
echo -e "	gcr: gnome3 backend"
echo -e " "
