#!/bin/bash

P_VERSION=5.26.2
BUILD_VERSION=1

LIST="libkscreen
libksysguard
bluedevil
kdecoration
kde-gtk-config
oxygen-sounds
ksystemstats
kactivitymanagerd
milou
layer-shell-qt
kscreenlocker
breeze
kwin
plasma-integration
kwayland-integration
plasma-workspace
kde-cli-tools
kdeplasma-addons
systemsettings
kgamma5
breeze-gtk
discover
drkonqi
khotkeys
kinfocenter
kmenuedit
kscreen
ksshaskpass
kwallet-pam
kwrited
oxygen
plasma-browser-integration
plasma-nm
powerdevil
polkit-kde-agent
plasma-desktop
plasma-disks
plasma-firewall
plasma-pa
plasma-sdk
plasma-systemmonitor
plasma-thunderbolt
plasma-vault
plasma-workspace-wallpapers
sddm-kcm
xdg-desktop-portal-kde"

CWD=~
STARTD=`pwd`

LOGFILE=~/build.log

echo "============================= Начало сборки kde-plasma $P_VERSION `date` =============================" >> $LOGFILE

for i in $LIST ; do
    cd $STARTD/$i
    if mkpkg -ba -wd ~/mkpkg/build -pod ~/mkpkg/repository/kde-plasma -si -bv $P_VERSION -bb $BUILD_VERSION; then
           echo "`date` || Пакет: $i ГОТОВ" >> $LOGFILE
           cd $STARTD
    else
           echo "`date` || ОШИБКА пакет: $i НЕ СОБРАН!!!" >> $LOGFILE
           cd $STARTD
    fi
done

echo "============================= kde-plasma $P_VERSION завершено `date` =============================" >> $LOGFILE
