echo -e "\n"
echo -e "The following packages extend ark capabilities:"
echo -e "    p7zip: 7Z format support"
echo -e "    unrar: RAR decompression support"
echo -e "    unarchiver: RAR format support"
echo -e "    lzop: LZO format support"
echo -e "    lrzip: LRZ format support"
echo -e "    arj: ARJ format support"
echo -e " "
