echo -e "\n"
echo -e "The following packages extend capabilities:"
echo -e "    plasma-workspace-wallpapers: additional wallpapers"
echo -e "    gpsd: GPS based geolocation"
echo -e "    networkmanager-qt: IP based geolocation"
echo -e "    kdepim-addons: displaying PIM events in the calendar"
echo -e "    appmenu-gtk-module: global menu support for GTK2 and some GTK3 applications"
echo -e "    baloo: Baloo search runner"
echo -e "    discover manage applications installation from the launcher"
echo -e " "
