#!/usr/bin/openrc-run

depend() {
	need dbus

	# Убедимся, что elogind включен, прежде чем xdm запустит любой dm
	before xdm
}

start() {
	ebegin "Starting elogind"

	start-stop-daemon --start --quiet \
		--pidfile "${ELOGIND_PIDFILE}" \
		--exec "${ELOGIND_EXEC}" -- --daemon
	eend $?
}

stop() {
	ebegin "Stopping elogind"
	start-stop-daemon --stop --quiet --pidfile "${ELOGIND_PIDFILE}"
	eend $?
}
