echo -e "\n"
echo -e "The following packages extend k3b capabilities:"
echo -e "    cdrtools: for CD burning with cdrecord"
echo -e "    dvd+rw-tools: for DVD burning support"
echo -e "    vcdimager: for VCD burning support"
echo -e "    emovix: for bootable multimedia CD/DVD support"
echo -e "    cdrdao: for disk-at-once (DAO) mode support"
echo -e "    cdparanoia: for CD ripping support"
echo -e "    transcode: for DVD ripping support"
echo -e " "

