echo -e " "
echo -e "The following packages extend claws-mail capabilities:"
echo -e "    python: needed for some tools"
echo -e "    perl: needed for some tools and perl plugin"
echo -e "    spamassassin: adds support for spamfiltering"
echo -e "    bogofilter: adds support for spamfiltering"
echo -e "    libnotify: for notification plugin"
echo -e "    libcanberra: for notification plugin"
echo -e "    dbus:for notification plugin"
echo -e "    libxml2: for rssyl plugins"
echo -e "    curl:for vcalendar, rssyl and spamreport plugins"
echo -e "    libarchive: for archive plugin and various other plugins"
echo -e "    libytnef: for tnef_parse plugin"
echo -e "    libgdata: for gdata plugin"
echo -e "    poppler-glib: for pdf viewer plugin"
echo -e "    ghostscript: for pdf viewer plugin"
echo -e "    libical: for vcalendar plugin"
echo -e "    dillo: for dillo html viewer plugin"
echo -e "    webkit2gtk: for fancy webkit html viewer plugin"
echo -e "    gumbo-parser: for litehtml plugin"
echo -e " "
