echo -e "\n"
echo -e "The following packages extend jack capabilities:"
echo -e "    a2jmidid: for ALSA MIDI to JACK MIDI bridging"
echo -e "    libffado: for firewire support using FFADO"
echo -e "    jack-example-tools: for official JACK example-clients and tools"
echo -e "    jack-dbus: for dbus integration"
echo -e "    jack-docs: for developer documentation"
echo -e "    realtime-privileges: for realtime privileges"
echo -e " "
