echo -e " "
echo -e "The following packages extend openoffice capabilities:"
echo -e "apr-util: adds apr support"
echo -e "java-environment: adds java support"
echo -e "gconf: adds additional gnome support"
echo -e "gstreamer0.10-base: some gstr-plugins to support multimedia content, e.g. in impress"
echo -e "mesa: for the OGLTrans extension of impress"
echo -e "mime-types: provides /etc/mime.types"
echo -e "nss: adds support for signed files/macros"
echo -e "python2: adds python support"
echo -e "raptor1: adds rdf support"
echo -e "sqlite: adds sqlite support"
echo -e " "
