echo -e "\n"
echo -e "The following packages extend kate capabilities:"
echo -e "    konsole: open a terminal in Kate"
echo -e "    clang: C and C++ LSP support"
echo -e "    python-lsp-server: Python LSP support"
echo -e "    texlab: LaTeX LSP support"
echo -e "    rust: Rust LSP support"
echo -e "    git: git-blame plugin"
echo -e " "
