echo -e " "
echo -e "The following packages extend qtcreator capabilities:"
echo -e "qt6-doc: integrated Qt documentation"
echo -e "qt6-examples: welcome page examples"
echo -e "gdb: debugger"
echo -e "cmake: cmake project support"
echo -e "x11-ssh-askpass: ssh support"
echo -e "git: git support"
echo -e "mercurial: mercurial support"
echo -e "bzr: bazaar support"
echo -e "valgrind: analyze support"
echo -e "perf: performer analyzer"
echo -e "mlocate: locator filter"
echo -e " "
