echo -e "\n"
echo -e "The following packages extend pulseaudio capabilities:"
echo -e "pulseaudio-alsa: ALSA configuration (recommended)"
echo -e "pulseaudio-zeroconf: Zeroconf support"
echo -e "pulseaudio-lirc: IR (lirc) support"
echo -e "pulseaudio-jack: Jack support"
echo -e "pulseaudio-bluetooth: Bluetooth support"
echo -e "pulseaudio-equalizer: Graphical equalizer"
echo -e "pulseaudio-rtp: RTP and RAOP support"
echo -e " "
