echo -e "\n"
echo -e "The following packages extend imagemagick capabilities:"
echo -e "    ghostscript: PS/PDF support"
echo -e "    libheif: HEIF support"
echo -e "    libjxl: JPEG XL support"
echo -e "    libraw: DNG support"
echo -e "    librsvg: SVG support"
echo -e "    libwebp: WEBP support"
echo -e "    libwmf: WMF support"
echo -e "    libxml2: Magick Scripting Language"
echo -e "    libzip: OpenRaster support"
echo -e "    ocl-icd: OpenCL support"
echo -e "    openexr: OpenEXR support"
echo -e "    openjpeg2: JPEG2000 support"
echo -e "    djvulibre: DJVU support"
echo -e "    pango: Text rendering"
echo -e ""
