printf "\nTo setup system connections, regular users must be member of 'netdev' group."

echo -e "\n"
echo -e "The following packages extend networkmanager capabilities:"
echo -e "polkit: let non-root users control networking"
echo -e "dnsmasq: connection sharing"
echo -e "nftables: connection sharing"
echo -e "iptables: connection sharing"
echo -e "bluez: Bluetooth support"
echo -e "ppp: dialup connection support"
echo -e "modemmanager: cellular network support"
echo -e "iwd: wpa_supplicant alternative"
echo -e "dhclient: alternative DHCP client"
echo -e "dhcpcd: alternative DHCP client"
echo -e "openresolv: alternative resolv.conf manager"
echo -e "firewalld: firewall support"
echo -e " "
