echo -e "\n"
echo -e "The following packages extend lximage-qt capabilities:"
echo -e "qt5-imageformats: support for additional image formats (WEBP, TIFF, etc.)"
echo -e "kimageformats: support for additional image formats (PCX, XCF, etc.)"
echo -e " "
