#!/usr/bin/openrc-run

description="libvirt virtual machine logging manager"
command="/usr/bin/virtlogd"
start_stop_daemon_args="-b"
pidfile="/run/virtlogd.pid"

extra_started_commands="reload"
description_reload="re-exec the daemon, while maintaining open connections"


depend() {
    after ntp-client ntpd nfs nfsmount corosync
}

reload() {
    ebegin "re-exec() virtlogd"

    start-stop-daemon --signal SIGUSR1 \
      --exec "${command}" --pidfile "${pidfile}"
}
