echo -e "\n"
echo -e "The following packages extend kdeplasma-addons capabilities:"
echo -e "    purpose: Quickshare applet"
echo -e "    quota-tools: disk quota applet"
echo -e "    qt5-webengine: dictionary and webbrowser applets"
echo -e " "
