echo -e "\n"
echo -e "The following packages extend sox capabilities:"
echo -e "libao: for ao plugin"
echo -e "libmad: for mp3 plugin"
echo -e "libid3tag: for mp3 plugin"
echo -e "wavpack: for wavpack plugin"
echo -e "libpulse: for pulse plugin"
echo -e "opusfile: for opus plugin"
echo -e "twolame: for mp3 plugin"
echo -e " "
