echo -e "\n"
echo -e "The following packages extend kpmcore capabilities:"
echo -e "    e2fsprogs: ext2/3/4 support"
echo -e "    xfsprogs: XFS support"
echo -e "    jfsutils: JFS support"
echo -e "    reiserfsprogs: Reiser support"
echo -e "    ntfs-3g: NTFS support"
echo -e "    dosfstools: FAT32 support"
echo -e "    fatresize: FAT resize support"
echo -e "    f2fs-tools: F2FS support"
echo -e "    exfat-utils: exFAT support"
echo -e "    exfatprogs: exFAT support (alternative to exfat-utils)"
echo -e "    nilfs-utils: nilfs support"
echo -e "    udftools: UDF support"
echo -e " "
