echo -e " "
echo -e "The following packages extend flacon capabilities:"
echo -e "alacenc: For ALAC support"
echo -e "faac: For AAC support"
echo -e "flac: For FLAC support"
echo -e "lame: For MP3 support"
echo -e "mac: For APE support"
echo -e "opus-tools: For OPUS support"
echo -e "sox: For SoX support"
echo -e "ttaenc: For TrueAudio support"
echo -e "vorbis-tools: For OGG support"
echo -e "wavpack: For WavPack support"
echo -e " "
