echo -e "\n"
echo -e "The following packages extend ktorrent capabilities:"
echo -e "    plasma-workspace: shutdown plugin"
echo -e "    kdnssd: zeroconf plugin"
echo -e "    taglib: mediaplayer plugin"
echo -e "    geoip: info widget plugin"
echo -e "    syndication: syndication plugin"
echo -e "    kplotting: statistics plugin"
echo -e " "

