echo -e "\n"
echo -e "The following packages extend gimp capabilities:"
echo -e "gutenprint: for sophisticated printing only as gimp has built-in cups print support"
echo -e "poppler-glib: for pdf support"
echo -e "alsa-lib: for MIDI event controller module"
echo -e "curl: for URI support"
echo -e "ghostscript: for postscript support"
echo -e "gvfs: for HTTP/S support (and many other schemes)"
echo -e " "
