echo -e "\n"
echo -e "The following packages extend mlt capabilities:"
echo -e "sdl_image: SDL1 plugin"
echo -e "sdl2: SDL2 plugin"
echo -e "libsamplerate: libavresample plugin"
echo -e "sox: SOX (Audio Swiss Army Knife) plugin"
echo -e "ffmpeg: ffmpeg plugin"
echo -e "vid.stab: video stabilize plugin"
echo -e "qt5-svg: Qt5 plugins"
echo -e "jack: JACK sound output plugin"
echo -e "ladspa: LADSPA plugins"
echo -e "libexif: auto rotate plugin"
echo -e "frei0r-plugins: for additional effects"
echo -e "movit: opengl plugin"
echo -e "opencv: openCV plugin"
echo -e "rubberband: audio pitch plugin"
echo -e "gdk-pixbuf: gdk plugin"
echo -e "pango: gdk plugin"
echo -e "rtaudio: rtaudio plugin"
echo -e "python: python bindings"
echo -e " "

