echo -e "\n"
echo -e "The following packages extend deadbeef capabilities:"
echo -e "alsa-oss: for OSS output plugin"
echo -e "cdparanoia: for cd audio plugin"
echo -e "curl: for last.fm, vfs_curl (shoutcast/icecast), artwork plugins"
echo -e "dbus: for notification daemon support (OSD current song notifications)"
echo -e "faad2: for AAC plugin"
echo -e "ffmpeg: for ffmpeg plugin"
echo -e "flac: for flac plugin"
echo -e "imlib2: for artwork plugin"
echo -e "libcddb: for cd audio plugin"
echo -e "libcdio: for cd audio plugin"
echo -e "libice: optional dependency for gtkui session client support"
echo -e "libmad: for mp3 plugin (mpeg1,2 layers1,2,3)"
echo -e "libogg: for ogg vorbis plugin"
echo -e "libsamplerate: for dsp_libsrc plugin (resampler)"
echo -e "libsidplay: for SID player plugin"
echo -e "libsm: optional dependency for gtkui session client support"
echo -e "libsndfile: for sndfile plugin"
echo -e "libvorbis: for ogg vorbis plugin"
echo -e "libx11: for global hotkeys plugin"
echo -e "libzip: for vfs_zip plugin"
echo -e "mpg123: for MP1/MP2/MP3 playback"
echo -e "opusfile: for opus plugin"
echo -e "pulseaudio: for PulseAudio output plugin"
echo -e "wavpack: for wavpack plugin"
echo -e "yasm: required to build assembly portions of ffap plugin"
echo -e "zlib: for Audio Overload plugin (psf, psf2, etc), GME (for vgz)"
echo -e " "
