echo -e "\n"
echo -e "The following packages extend lib32-alsa-plugins capabilities:"
echo -e "    lib32-dbus: for maemo plugin"
echo -e "    lib32-jack: for pcm_jack plugin"
echo -e "    lib32-libavtp: for pcm_aaf plugin"
echo -e "    lib32-libsamplerate: for rate_samplerate plugin"
echo -e "    lib32-libpulse: for conf_pulse, ctl_pulse and pcm_pulse plugins"
echo -e "    lib32-speexdsp: for pcm_speex and rate_speexrate plugins"
echo -e " "
