echo -e "\nThe following packages extend purpose capabilities:"
echo -e "kdeconnect: sharing to smartphone via KDE Connect"
echo -e "telegram-desktop: sharing via Telegram"
echo -e "bluedevil: sharing via Bluetooth"
echo -e "prison: QR code plugin"
echo -e " "
