echo -e "\n"
echo -e "The following packages extend python-dnspython capabilities:"
echo -e "python-cryptography: DNSSEC support"
echo -e "python-requests-toolbelt: DoH support"
echo -e "python-idna: support for updated IDNA 2008"
echo -e "python-curio: async support"
echo -e "python-trio: async support"
echo -e "python-sniffio: async support"
echo -e " "
