echo -e "\n"
echo -e "The following packages extend kdevelop capabilities:"
echo -e "    konsole: embedded terminal"
echo -e "    git: Git support"
echo -e "    subversion: SVN support"
echo -e "    gdb: GNU debugger support"
echo -e "    lldb: LLDB debugger support"
echo -e "    qt5-doc: Qt documentation integration"
echo -e "    cmake: cmake integration"
echo -e "    meson: meson integration"
echo -e "    qt5-tools: qthelp plugin"
echo -e "    okteta: GNU debugger support"
echo -e "    plasma-framework: for the plasma addons"
echo -e "    purpose: patch review plugin"
echo -e "    astyle: astyle plugin"
echo -e "    cppcheck: code analyzer"
echo -e "    heaptrack: memory profiler"
echo -e "    clazy: clazy analyzer plugin"
echo -e "    kio-extras: man pages plugin"
echo -e " "
