echo -e " "
echo -e "The following packages extend far2l capabilities:"
echo -e "libxi: TTY X11 backend"
echo -e "openssl: FTPS support in NetRocks"
echo -e "libssh: SFTP support in NetRocks"
echo -e "smbclient: SMB support in NetRocks"
echo -e "libnfs: NFS support in NetRocks"
echo -e "neon: WebDAV support in NetRocks"
echo -e "pcre: custom archives support in multiarc"
echo -e "libarchive: more archive type support in multiarc"
echo -e " "
