echo -e " "
echo -e "The following packages extend beets capabilities:"
echo -e "bash-completion: Bash completion"
echo -e "chromaprint: Chromaprint/Acoustid plugin"
echo -e "ffmpeg: Convert, ReplayGain plugins"
echo -e "gst-plugins-bad: Chromaprint/Acoustid, BPD, ReplayGain plugins"
echo -e "gst-plugins-good: Chromaprint/Acoustid, BPD, ReplayGain plugins"
echo -e "gst-plugins-ugly: Chromaprint/Acoustid, BPD, ReplayGain plugins"
echo -e "gst-libav: Chromaprint/Acoustid, BPD, ReplayGain plugins"
echo -e "gst-python: Chromaprint/Acoustid, BPD, ReplayGain plugins"
echo -e "imagemagick: Thumbnails plugin"
echo -e "python-beautifulsoup4: Lyrics plugin"
echo -e "python-discogs-client: Discogs plugin"
echo -e "python-flask: Web plugin"
echo -e "python-gobject: ReplayGain plugin"
echo -e "python-mpd2: MPDStats plugin"
echo -e "python-pyacoustid: Chromaprint/Acoustid plugin"
echo -e "python-pylast: LastGenre plugin"
echo -e "python-requests: Chromaprint/Acoustid, BPD, FetchArt plugins"
echo -e "python-requests-oauthlib: Beatport plugin"
echo -e "python-xdg: Thumbnails plugin"
echo -e " "
