echo -e "\n"
echo -e "The following packages extend xine-lib capabilities:"
echo -e "libdvdnav: for dvd plugin"
echo -e "libdvdread: for spu and dxr3 plugins"
echo -e "vcdimager: for vcd plugin"
echo -e "glu: for opengl and vaapi plugins"
echo -e "sdl: for sdl plugin"
echo -e "'wayland: for egl_wl plugin"
echo -e "aalib: for aalib plugin"
echo -e "a52dec: for a52 plugin"
echo -e "faad2: for faad plugin"
echo -e "flac: for flac plugin"
echo -e "libdca: for dts (dca) plugin"
echo -e "libmad: for mad (mp3) plugin"
echo -e "libmpcdec: for mpc (musepack) plugin"
echo -e "wavpack: for wavpack plugin"
echo -e "gdk-pixbuf: for gdk_pixbuf plugin"
echo -e "imagemagick: for imagemagick plugin"
echo -e "libcaca: for caca plugin"
echo -e "libmng: for mng plugin"
echo -e "libnfs: for nfs plugin"
echo -e "libssh2: for ssh plugin"
echo -e "smbclient: for samba plugin"
echo -e " "
