echo -e "\n"
echo -e "The following packages extend kuserfeedback capabilities:"
echo -e "qt5-declarative: QML bindings"
echo -e "qt5-charts: User Feedback console"
echo -e "qt5-svg: User Feedback console"
echo -e " "
