echo -e "\n"
echo -e "The following packages extend clementine capabilities:"
echo -e "gst-plugins-base: Base plugin libraries"
echo -e "gst-plugins-good: Good plugin libraries"
echo -e "gst-plugins-bad: Bad plugin libraries"
echo -e "gst-plugins-ugly: Ugly plugin libraries"
echo -e "gst-libav: Libav plugin"
echo -e "gvfs: Various devices support"
echo -e " "
