echo -e "\n"
echo -e "The following packages extend avidemux capabilities:"
echo -e "lame: for the corresponding audio encoder plugin"
echo -e "faac: for the corresponding audio encoder plugin"
echo -e "faad2: for the corresponding audio decoder plugin"
echo -e "opus: for the corresponding audio decoder plugin"
echo -e "opencore-amr: for the corresponding audio decoder plugin"
echo -e "jack: for the corresponding audio device plugin"
echo -e "libpulse: for the corresponding audio device plugin"
echo -e "x264: for the corresponding video encoder plugin"
echo -e "libx264: for the corresponding video encoder plugin"
echo -e "x265: for the corresponding video encoder plugin"
echo -e "xvidcore: for the corresponding video encoder plugin"
echo -e "qt5-base: for the QtScript scripting support"
echo -e "libdca: for the corresponding audio decoder plugin"
echo -e "libfdk-aac: for the corresponding audio decoder plugin"
echo -e "twolame: for the corresponding audio decoder plugin"
echo -e "libass: for the corresponding video filter plugin"
echo -e "fribidi: for the corresponding video filter plugin"
echo -e " "
