echo -e " "
echo -e "The following packages extend python-qtpy capabilities:"
echo -e "python-pyqt5: Qt5 Python bindings"
echo -e "python-pyqt6: Qt6 Python bindings"
echo -e "python-pyqt5-webengine: Qt5-WebEngine python bindings"
echo -e "python-pyqt6-webengine: Qt6-WebEngine python bindings"
echo -e "pyside2: PySide Qt5 Python bindings"
echo -e "pyside6: PySide Qt6 Python bindings"
echo -e " "
