echo -e "\n"
echo -e "The following packages extend postgresql capabilities:"
echo -e "    python: for PL/Python 3 support"
echo -e "    perl: for PL/Perl support"
echo -e "    tcl: for PL/Tcl support"
echo -e "    postgresql-old-upgrade: upgrade from previous major version using pg_upgrade"
echo -e "    logrotate: rotates system logs automatically"
echo -e " "
