#!/usr/bin/openrc-run

PIDFILE=/var/run/git-daemon.pid

depend() {
	need net
	use logger
}

start() {
	ebegin "Starting git-daemon"
		start-stop-daemon --start --quiet --background \
		--pidfile ${PIDFILE} \
		--exec /usr/bin/git -- daemon \
			--pid-file=${PIDFILE} \
			--user=${GIT_USER} --group=${GIT_GROUP} \
			${GITDAEMON_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping git-daemon"
		start-stop-daemon --stop --quiet \
		--pidfile ${PIDFILE}
	eend $?
}
